wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
hidden_size:
  value: 32
lr:
  value: 0.001
num_hidden_layer:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0.5
weight_init:
  value: xavier
