wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
hidden_size:
  value: 64
lr:
  value: 0.0001
num_hidden_layer:
  value: 5
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
weight_init:
  value: random
