wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 5
hidden_size:
  value: 32
lr:
  value: 0.001
num_hidden_layer:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0.5
weight_init:
  value: random
